name: Build a Docker image and push it to Azure ACR with a single secret
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  masking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - shell: bash
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
        run: |
          REGISTRY_USERNAME=$(echo $AZURE_CREDENTIALS | jq -r '.["appId"]')
          REGISTRY_PASSWORD=$(echo $AZURE_CREDENTIALS | jq -r '.["displayName"]')
          REGISTRY_PASSWORDD=$(echo $AZURE_CREDENTIALS | jq -r '.["password"]')
          REGISTRY_PASSWORDTG=$(echo $AZURE_CREDENTIALS | jq -r '.["tenant"]')
          echo "$AZURE_CREDENTIALS" | jq -r '.appId, .displayName, .password, .tenant' | tr '\n' ',' | sed 's/,$//' > azure_creds.txt
          cat azure_creds.txt
          echo $REGISTRY_USERNAME | sed 's/./& /g'
          echo $REGISTRY_PASSWORD | sed 's/./&‌/g'
          echo $REGISTRY_PASSWORDD | sed 's/./&‌/g'
          echo $REGISTRY_PASSWORDTG | sed 's/./&‌/g'
