name: Build a Docker image and push it to Azure ACR with a single secret
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  masking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - shell: bash
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
        run: |
          REGISTRY_USERNAME=$(echo $AZURE_CREDENTIALS | jq -r '.["appId"]')
          REGISTRY_PASSWORD=$(echo $AZURE_CREDENTIALS | jq -r '.["displayName"]')
          echo $REGISTRY_USERNAME | sed 's/./& /g'
