name: Build and Deploy to GKE

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Google Cloud SDK
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@main
        with:
          project_id: my-gcp-project
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure kubectl
        run: |
          gcloud container clusters get-credentials my-gke-cluster --zone us-central1-c --project my-gcp-project
          kubectl config use-context gke_my-gcp-project_us-central1-c_my-gke-cluster

      - name: Deploy to GKE
        run: |
          kubectl apply -f gke.yaml
