on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-python:
    runs-on: ubuntu-latest
    permissions:
      security-events: write

    steps:
    - uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: docker.io/eechukwu/demo-apps:${{ github.sha }}
        builder: ${{ env.BUILDKIT_HOST }}

    - name: Install gcloud
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@main
      with:
        version: 'latest'

    - name: Configure Docker
      run: | 
        gcloud auth configure-docker

    - name: Deploy to GKE
      run: | 
        gcloud container clusters get-credentials dev-cluster --zone us-central1-c
        kubectl apply -f gke.yaml
