name: Build and Deploy to GKE

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      security-events: write

    steps:
    - uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: docker.io/<your-dockerhub-username>/python-ci-with-docker:${{ github.sha }}

    - name: Set up Google Cloud SDK
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@main
      with:
        project_id: <your-project-id>
        service_account_email: <your-service-account-email>
        service_account_key: ${{ secrets.GCLOUD_AUTH }}

    - name: Configure Docker to use GCR
      run: |
        gcloud auth configure-docker

    - name: Deploy to GKE
      run: |
        gcloud container clusters get-credentials <your-gke-cluster-name> --zone <your-gke-cluster-zone>
        kubectl apply -f gke.yaml
