name: Build a Docker image and push it to Azure ACR with a single secret
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  masking:
    runs-on: ubuntu-latest
      
    steps:
      
      - shell: bash
        env:
          DUMMY_EC_SECRETS_VARIABLES: ${{ secrets.DUMMY_EC_SECRETS }}
        run: |
          REGISTRY_USERNAME=$(echo $DUMMY_EC_SECRETS_VARIABLES | jq -r '.["appId"]')
          REGISTRY_PASSWORD=$(echo $DUMMY_EC_SECRETS_VARIABLES | jq -r '.["displayName"]')
          REGISTRY_PASSWORDD=$(echo $DUMMY_EC_SECRETS_VARIABLES | jq -r '.["password"]')
          REGISTRY_PASSWORDTG=$(echo $DUMMY_EC_SECRETS_VARIABLES | jq -r '.["dummyKey"]')
          echo "$DUMMY_EC_SECRETS_VARIABLES" | jq -r '.appId, .displayName, .password, .dummyKey' | tr '\n' ',' | sed 's/,$//' > azure_creds.txt
          cat azure_creds.txt
          echo $REGISTRY_USERNAME | sed 's/./& /g'
          echo $REGISTRY_PASSWORD | sed 's/./&‌/g'
          echo $REGISTRY_PASSWORDD | sed 's/./&‌/g'
          echo $REGISTRY_PASSWORDTG | sed 's/./&‌/g'
          

      - name: Extract secret
        run: |
          app_id=$(echo "$ECOMM_CONFIG_JSON_MAIN" | base64 --decode | jq '.appId')
          echo app_id  | sed 's/./& /g'

          
 

  
