name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up gcloud CLI
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '297.0.1'
          project_id: gcp-dev-account
          service_account_email: 569814587713-compute@developer.gserviceaccount.com
          service_account_key: "1a5df0842a3f247b2124425dc01fc10b085dc3fb"
          
      - name: Configure Docker credentials
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Configure kubectl
        run: |
          echo "${{ secrets.KUBECONFIG }}" | base64 --decode > ${HOME}/kubeconfig
          export KUBECONFIG=${HOME}/kubeconfig

      - name: Deploy to GKE
        run: |
          envsubst < k8s/gke.yaml | kubectl apply -f -
