name: Build and Deploy

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: my-gcp-project
  IMAGE_NAME: python-ci-docker
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up gcloud CLI
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Build the Docker image
        run: |
          docker build -t gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .

      - name: Push the Docker image
        uses: GoogleCloudPlatform/docker-credential-gcr@master
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
        run: |
          docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Deploy to GKE
        uses: GoogleCloudPlatform/github-actions/deploy-gke@master
        with:
          credentials: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ env.PROJECT_ID }}
          cluster_name: my-gke-cluster
          location: us-central1-a
          yaml_file: ./gke.yaml
