name: Python CI with Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-python:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Update package list and dependencies
      run: sudo apt-get update

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: eechukwu/demo-apps:${{ github.sha }}
