name: Python CI with Docker and GKE

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-python:
    runs-on: ubuntu-latest
    permissions:
      security-events: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: eechukwu/demo-apps:${{ github.sha }}
        builder: ${{ env.BUILDKIT_HOST }}

    - name: Configure Google Cloud SDK
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@main
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: my-project-id
        zone: us-central1-a
        cluster_name: my-cluster-name

    - name: Deploy to GKE
      run: |
        gcloud config set project my-project-id
        gcloud container clusters get-credentials my-cluster-name --zone us-central1-a
        kubectl apply -f gke.yaml
