name: Build and Deploy to GKE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: dev-cluster    # Add your cluster name here.
  GKE_ZONE: us-central1-c   # Add your cluster zone here.

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: eechukwu/demo-apps:${{ github.sha }}
          builder: ${{ env.BUILDKIT_HOST }}

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@1.6.1
        with:
          project_id: ${{ secrets.GKE_PROJECT }}
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker to use gcloud command-line tool as credential helper for authentication
        run: |-
          gcloud --quiet auth configure-docker

      - name: Get the GKE credentials so we can deploy to the cluster
        uses: google-github-actions/get-gke-credentials@1.4.0
        with:
          project_id: ${{ secrets.GKE_PROJECT }}
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          service_account_key: ${{ secrets.GKE_SA_KEY }}

      - name: Deploy to GKE
        run: |-
          kubectl apply -f gke.yaml
          kubectl get services -o wide
